Repository ahmadauf98/buefy-shop, pull requests merged in 2021-01, with the labels that each got.

#4 Add realtime feeding courier rating
  .firebaserc
  .gitignore
  firebase.json
  functions/.gitignore
  functions/index.js
  functions/package-lock.json
  functions/package.json
  functions/web_scrappers/trackingmore.js
  pages/courier/_courier_id.vue
  pages/products/_product_id.vue
  pages/products/_slug.vue
  pages/seller/order/myorders.vue
  pages/seller/order/ordercancellation.vue
  pages/seller/shipment/myshipment.vue
  pages/seller/shipment/shipmentsettings.vue
Labels: evolution

#6 Modify shopping cart
  components/CartProductListItem/CartProductListItem.vue
  components/Header/Header.vue
  pages/cart.vue
  pages/cart/index.vue
  pages/products/_product_id.vue
Labels: maintenance

#8 Fix Bugs - User Logout Issues
  components/Header/Header.vue
Labels: bugs

#9 Improve UI of Search Bar
  components/Hero.vue
Labels: improve ui

#10 Adding Seller Page (Shipment Settings)
  package.json
  pages/buyer/signup.vue
  pages/index.vue
  pages/products/_product_id.vue
  pages/seller/product/addproduct.vue
  pages/seller/shipment/shipmentsettings.vue
  yarn.lock
Labels: improve ui, maintenance

#12 Modify Cart Page - Checkout
  components/Checkout/Checkout.vue
  package-lock.json
  pages/cart/index.vue
  store/index.js
Labels: maintenance

#14 Adding Seller Page (My Shipment)
  components/Tab/Tab.vue
  components/Tab/index.js
  pages/seller/shipment/myshipment.vue
Labels: maintenance

#15 Adding alert snackbar for login and signup page
  components/notifications.vue
  pages/buyer/login.vue
  pages/buyer/signup.vue
  store/index.js
Labels: maintenance

#17 Seller report dashboard & Overlay for shop name
  components/Header/Header.vue
  components/buyerSidebar/buyerSidebar.vue
  components/buyerSidebar/index.js
  components/buyerWelcome/buyerWelcome.vue
  components/buyerWelcome/index.js
  pages/buyer/buyercenter.vue
  pages/buyer/report/completeds.vue
  pages/buyer/report/receiveds.vue
  pages/buyer/report/shippeds.vue
  pages/seller/index.vue
  pages/seller/product/myproducts.vue
Labels: maintenance

#20 fix issue and enhancement - product,fee,console
  components/CartProductListItem/CartProductListItem.vue
  components/Checkout/Checkout.vue
  pages/cart/index.vue
  pages/products/_product_id.vue
Labels: code enhancement, maintenance

#22 Fix highest Price Range Slider
  components/Sidebar/Sidebar.vue
  pages/seller/index.vue
Labels: maintenance

#23 Buyer Purchase dashboard update
  components/buyerSidebar/buyerSidebar.vue
  pages/buyer/buyercenter.vue
  pages/buyer/report/cancelled.vue
  pages/buyer/report/completedbuyer.vue
  pages/buyer/report/completeds.vue
  pages/buyer/report/receiveds.vue
  pages/buyer/report/shippeds.vue
  pages/buyer/report/shipping.vue
  pages/buyer/report/toship.vue
Labels: maintenance

#25 Fix bugs - Highest Price Issue
  components/Sidebar/Sidebar.vue
Labels: bugs

#27 Shipping Information error handling
  package-lock.json
  package.json
  pages/cart/index.vue
Labels: bugs, maintenance

#28 Added error handling on Buyer Profile page
  package-lock.json
  pages/buyer/account/profile.vue
  pages/cart/index.vue
Labels: bugs, maintenance
